import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from "next/image";
import { useRouter } from "next/router";

// Client connection
import { menuItems } from '@/components/Header/menuItems';
import { client } from "@/lib/client";
import { mainMenuQueriesObjCreator, chapterPageQuery, slugCurrent, newsQuery } from '@/lib/queries';
import { menuCreator, menuItemsMerger } from '@/lib/menuCreator';

import { urlFor } from "../../lib/client";

import BlockContent from "@sanity/block-content-to-react";

// Components
import Header from '@/components/Header/Header';
import { Breadcrumbs } from "@/components/Breadcrumbs/Breadcrumbs";
import PageContentSection from '@/components/PageContentSection/PageContentSection';

// Other libs
import moment from "moment";


const InternationalActivityPage = ({
  referencesData,
  mainMenuQO,
  // newsArr,
}) => {

  const [newsArrForMap, setNewsArrForMap] = useState([]);

  const {
    title,
    slug,
  } = referencesData;


  // const router = useRouter();

  // const { asPath } = router;

  // // Фільтрую і сортую масив (по academicMobilityBool)
  // const filteredArrayAcademicMobility = newsArr.filter((item) => item.academicMobilityBool);
  // const sortedArrayAcademicMobility = filteredArrayAcademicMobility.sort(
  //   (a, b) => moment(b.publishedDate).format("YYYYMMDDHHmm") - moment(a.publishedDate).format("YYYYMMDDHHmm")
  // );

  // // Фільтрую і сортую масив (по intPractOfStudentsBool)
  // const filteredArrayIntPractOfStudents = newsArr.filter((item) => item.intPractOfStudentsBool);
  // const sortedArrayIntPractOfStudents = filteredArrayIntPractOfStudents.sort(
  //   (a, b) => moment(b.publishedDate).format("YYYYMMDDHHmm") - moment(a.publishedDate).format("YYYYMMDDHHmm")
  // );

  // // Фільтрую і сортую масив (по intInternshipBool)
  // const filteredArrayIntInternship = newsArr.filter((item) => item.intInternshipBool);
  // const sortedArrayIntInternship = filteredArrayIntInternship.sort(
  //   (a, b) => moment(b.publishedDate).format("YYYYMMDDHHmm") - moment(a.publishedDate).format("YYYYMMDDHHmm")
  // );

  // // Фільтрую і сортую масив (по eventsConferencesForumsBool)
  // const filteredArrayEventsConferencesForums = newsArr.filter((item) => item.eventsConferencesForumsBool);
  // const sortedArrayEventsConferencesForums = filteredArrayEventsConferencesForums.sort(
  //   (a, b) => moment(b.publishedDate).format("YYYYMMDDHHmm") - moment(a.publishedDate).format("YYYYMMDDHHmm")
  // );

  // // Фільтрую і сортую масив (по programsTrainingsProjectsBool)
  // const filteredArrayProgramsTrainingsProjects = newsArr.filter((item) => item.programsTrainingsProjectsBool);
  // const sortedArrayProgramsTrainingsProjects = filteredArrayProgramsTrainingsProjects.sort(
  //   (a, b) => moment(b.publishedDate).format("YYYYMMDDHHmm") - moment(a.publishedDate).format("YYYYMMDDHHmm")
  // );


  const [mainMenuArr, setMainMenuArr] = useState(menuItems);

  useEffect(() => {

    const menuObj = menuItemsMerger(
      menuItems,
      mainMenuQO,
    )

    setMainMenuArr((prevState) => {
      if (prevState) {
        return menuCreator(
          menuObj,
          prevState,
        )
      }
    });

    // ---------------------------------

    // if (asPath === "/international-activity/academic-mobility") {
    //   setNewsArrForMap(sortedArrayAcademicMobility);
    // }
    // if (asPath === "/international-activity/international-practice-of-students") {
    //   setNewsArrForMap(sortedArrayIntPractOfStudents);
    // }

    // --------------------------------------

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [referencesData, mainMenuQO]);

  return (
    <>
      <Head>
        <title>Кафедра електричної інженерії ТНТУ :: {title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Header mainMenuArr={mainMenuArr} />

      <Breadcrumbs
        chapterTitle="Посилання"
        pageTitle={title}
        pageUrl={slug.current}
      />

      {/* Page Content */}
      <PageContentSection data={referencesData} />

    </>
  )
}


export default InternationalActivityPage;

export async function getStaticPaths() {
  const query = slugCurrent('references');

  const pages = await client.fetch(query);
  const paths = pages.map((page) => ({
    params: {
      slug: page.slug.current
    }
  }));
  return {
    paths, fallback: 'blocking'
  }
}

export async function getStaticProps({ params: { slug } }) {
  const referencesData = await client.fetch(chapterPageQuery('references', slug));
  const mainMenuQO = await mainMenuQueriesObjCreator();
  // const newsArr = await client.fetch(newsQuery);

  return {
    props: {
      referencesData,
      mainMenuQO,
      // newsArr,
    }
  }
}