import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from "next/image";

// Client connection
import { menuItems } from '@/components/Header/menuItems';
import { client, clientConfig } from "@/lib/client";
import { itemsOrderAscTransform } from '@/lib/helpers';
import { chapterTitleQuery, chapterPageQuery, slugCurrent } from '@/lib/queries';
import { menuCreator } from '@/lib/menuCreator';

import { urlFor } from "../../lib/client";

import BlockContent from "@sanity/block-content-to-react";

// Components
import Header from '@/components/Header/Header';
import { Breadcrumbs } from "@/components/Breadcrumbs/Breadcrumbs";

// Other libs
import Lightbox from "yet-another-react-lightbox";
import "yet-another-react-lightbox/styles.css";


const AboutMTBPage = ({
  aboutItems,
  // aboutMTBItems,
  specialitiesItems,
  bachelorItems,
  masterItems,
  aboutMTBPage,
}) => {

  const [open, setOpen] = useState(false);
  const [mainMenuArr, setMainMenuArr] = useState(menuItems);

  // console.log(props);

  const { title, body, position, slug, } = aboutMTBPage;
  // const name = `${firstName} ${secondName} ${fatherName}`
  // const galleryArray = imageGallery.map(el => { return { src: urlFor(el).url() } })

  useEffect(() => {

    const menuItemsObj = {
      aboutItems,
      // aboutMTBItems,
      specialitiesItems,
      bachelorItems,
      masterItems,
      aboutMTBPage,
    }

    menuItemsMerger(menuItemsObj)

    const transformedAbout = itemsOrderAscTransform(aboutItems, menuItems[0].children);
    // const transformedAboutMTB = itemsOrderAscTransform(aboutMTBItems, menuItems[5].children);
    const transformedSpecialities = itemsOrderAscTransform(specialitiesItems, menuItems[1].children);
    const transformedBachelor = itemsOrderAscTransform(bachelorItems, menuItems[2].children);
    const transformedMaster = itemsOrderAscTransform(masterItems, menuItems[3].children);

    setMainMenuArr((prevState) => {
      if (prevState) {
        return menuCreator(
          transformedAbout,
          // transformedAboutMTB,
          transformedSpecialities,
          transformedBachelor,
          transformedMaster,
          prevState,
        )
      }
    });
  }, [aboutItems, bachelorItems, masterItems, specialitiesItems]);


  // console.log('mainMenuArr :>> ', mainMenuArr);

  return (
    <>
      <Head>
        <title>Кафедра електричної інженерії ТНТУ :: {title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Header mainMenuArr={mainMenuArr} />

      <Breadcrumbs
        chapterTitle="Про кафедру"
        pageTitle={title}
        pageUrl={slug.current.slice(6)}
      />

      {/* < !-- ======= Features Section ======= --> */}
      <section className="features my-personal">
        <div className="container" data-aos="fade-up">

          {/* <!-- Feature Icons --> */}
          <div className="row feature-icons" data-aos="fade-up">

            <div className="row gx-0">

              <h3>{title}</h3>

              <div className="col-xl-12 pt-2 px-2">
                <div className="row align-self-start content text-justify">
                  <div className="icon-box my-dstyle" data-aos="fade-up">

                    <BlockContent
                      blocks={body}
                      projectId={clientConfig.projectId}
                      dataset={clientConfig.dataset}
                    />

                  </div>
                </div>
              </div>

              {/* <div> */}
              {/* <Lightbox
                open={open}
                close={() => setOpen(false)}
                slides={galleryArray}
              /> */}
              {/* </div> */}

            </div>

          </div>
          {/* <!-- End Feature Icons --> */}

        </div >
      </section >
      {/* <!--End Features Section-- > */}
    </>
  )
}


export default AboutMTBPage;

export async function getStaticPaths() {
  const pages = await client.fetch(slugCurrent("about-mtb"));

  const paths = pages.map((aboutMTB) => ({
    params: {
      slug: aboutMTB.slug.current
    }
  }));
  return {
    paths, fallback: 'blocking'
  }
}

export async function getStaticProps({ params: { slug } }) {
  const aboutMTBPage = await client.fetch(chapterPageQuery("about-mtb", slug));

  const aboutItems = await client.fetch(chapterTitleQuery("about"));
  const aboutMTBItems = await client.fetch(chapterTitleQuery("about-mtb"));
  const specialitiesItems = await client.fetch(chapterTitleQuery("specialities"));
  const bachelorItems = await client.fetch(chapterTitleQuery("bachelor"));
  const masterItems = await client.fetch(chapterTitleQuery("master"));

  return {
    props: {
      aboutItems,
      aboutMTBItems,
      specialitiesItems,
      bachelorItems,
      masterItems,
      aboutMTBPage,
    }
  }
}