import { useState, useEffect } from "react";
import Head from 'next/head'
import { useRouter } from "next/router";
import { urlFor } from "../../../lib/client";
import Image from "next/image";
import BlockContent from "@sanity/block-content-to-react";

// Client connection
import { menuItems } from '@/components/Header/menuItems';
import { client, clientConfig } from "@/lib/client";
import { itemsOrderAscTransform } from '@/lib/helpers';
import { chapterTitleQuery, chapterItemQuery } from '@/lib/queries';
import { menuCreator } from '@/lib/menuCreator';

// Components
import Header from "/components/Header/Header";
import { Breadcrumbs } from "@/components/Breadcrumbs/Breadcrumbs";

// Other libs
import moment from "moment";
import { Lightbox } from "yet-another-react-lightbox";
import "yet-another-react-lightbox/styles.css";


const PersonInfo = ({
  personItem,
  aboutItems,
  specialitiesItems,
  bachelorItems,
  masterItems,
}) => {

  const [open, setOpen] = useState(false);

  // console.log(person);

  const { mainPhoto,
    firstName,
    secondName,
    fatherName,
    sciDegree,
    acadStatus,
    position,
    edGuarantee,
    education,
    achievements,
    experience,
    sciWork,
    sciInterests,
    publications,
    inventions,
    sciProjects,
    reviewing,
    reviewedDissertations,
    languages,
    internship,
    certificates,
    awards,
    teachingSubjectList,
    imageGallery,
    bio,
    slug,
  } = personItem;
  const name = `${firstName} ${secondName} ${fatherName}`
  const galleryArray = imageGallery.map(el => { return { src: urlFor(el).url() } })
  // console.log('galleryArray :>> ', galleryArray);
  // const date = format(new Date(post._createdAt), 'dd MMM yyyy');

  const router = useRouter();
  const { pathname } = router;

  // MENU FORMATION PART ==============================================

  const [mainMenuArr, setMainMenuArr] = useState(menuItems);

  useEffect(() => {

    const transformedAbout = itemsOrderAscTransform(aboutItems, menuItems[0].children);
    const transformedSpecialities = itemsOrderAscTransform(specialitiesItems, menuItems[1].children);
    const transformedBachelor = itemsOrderAscTransform(bachelorItems, menuItems[2].children);
    const transformedMaster = itemsOrderAscTransform(masterItems, menuItems[3].children);

    setMainMenuArr((prevState) => {
      if (prevState) {
        return menuCreator(
          transformedAbout, transformedSpecialities, transformedBachelor, transformedMaster,
          prevState,
        )
      }
    });
  }, [aboutItems, bachelorItems, masterItems, specialitiesItems]);



  // MENU FORMATION PART ENDS =========================================


  return (
    <>
      <Head>
        <title>Кафедра електричної інженерії ТНТУ :: {name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      {/* В хедер треба передавати вже сформований масив */}
      {pathname !== "/" && <Header mainMenuArr={mainMenuArr} />}

      <Breadcrumbs
        chapterTitle="Про кафедру"
        pageTitle="Колектив"
        pageUrl="/about/staff"
        subPageTitle={name}
        subPageUrl={slug.current}
      />

      {/* < !-- ======= Features Section ======= --> */}
      <section className="features my-personal">
        <div className="container" data-aos="fade-up">

          {/* <!-- Feature Icons --> */}
          <div className="row feature-icons" data-aos="fade-up">

            <div className="row gx-0">

              <h3>{name}</h3>

              <div className="col-xl-4 pt-2 px-2 d-flex" data-aos="fade-right" data-aos-delay="100">
                <div className="row align-self-start">
                  <a href="#"
                    className="image-container"
                    style={{ position: "relative" }}
                    onClick={() => setOpen(true)}
                  >
                    <Image
                      src={urlFor(mainPhoto).url()}
                      fill
                      priority
                      className="img-fluid rounded image"
                      alt={mainPhoto.caption}
                    />
                  </a>
                </div>
              </div>

              <div className="col-xl-8 pt-2 px-2">
                <div className="row align-self-start content text-justify">
                  <div className="icon-box my-dstyle" data-aos="fade-up">
                    <h4>Науковий ступінь: <span className="h5">{sciDegree}(напис має бути повністю))</span> </h4>
                    <h4>Вчене звання: <span className="h5">{acadStatus}</span> </h4>
                    <h4>Посада: <span className="h5">{position.long}</span> </h4>
                    <h4>Гарант освітньої програми:</h4>
                    <ul>{edGuarantee.map(el => (<li key={el}>{el}</li>))}</ul>


                    <hr />

                    <p>Посилання (може зробити картинками як було?) </p>

                    <hr />

                    <h4>Освіта:</h4>
                    <ul>{education.map(el => (
                      <li key={el._key}>
                        <p><strong>{el.university}</strong></p>
                        <BlockContent
                          blocks={el.description}
                          projectId={clientConfig.projectId}
                          dataset={clientConfig.dataset}
                        />
                      </li>
                    ))}
                    </ul>
                  </div>
                </div>
              </div>

              <div className="col-xl-12 pt-2 px-2">
                <div className="row align-self-start content text-justify">
                  <div className="icon-box my-dstyle" data-aos="fade-up">
                    <h4>Присудження наукового ступеня:</h4>
                    <p>Кандидат технічних наук, спеціальність 01.02.04 «Механіка деформівного твердого тіла», 2000 р. Диплом ДК 008799. Дисертаційне дослідження на тему: «Прогнозування динамічної повзучості алюмінієвого сплаву».</p>
                    <h4>Присудження наукового звання:</h4>
                    <p>Доцент кафедри менеджменту у виробничій сфері, 2008, атестат доцента ДЦ № 019187.</p>

                    <hr />

                    <h4>ПРОФЕСІЙНІ ЗДОБУТКИ:</h4>
                    <BlockContent
                      blocks={achievements}
                      projectId={clientConfig.projectId}
                      dataset={clientConfig.dataset}
                    />
                    <h4>ДОСВІД РОБОТИ:</h4>
                    <ul>
                      {experience.map(el =>
                        <li key={el._key}>
                          <p><strong>{el.jobPlace}</strong></p>
                          <p>{el.jobPosition}</p>
                        </li>
                      )}
                    </ul>

                    <hr />

                    <h4>НАУКОВА РОБОТА</h4>
                    <BlockContent
                      blocks={sciWork}
                      projectId={clientConfig.projectId}
                      dataset={clientConfig.dataset}
                    />
                    <p>[значення, але чи потрібне?] </p>
                    <h4>Наукові інтереси</h4>
                    <ul>
                      {sciInterests.map(el => <li key={el}>{el}</li>)}
                    </ul>
                    <h4>Публікації</h4>
                    <BlockContent
                      blocks={publications}
                      projectId={clientConfig.projectId}
                      dataset={clientConfig.dataset}
                    />
                    <h4>Винахідництво та раціоналізаторство</h4>
                    <BlockContent
                      blocks={inventions}
                      projectId={clientConfig.projectId}
                      dataset={clientConfig.dataset}
                    />

                    <h4>Наукові теми та проєкти</h4>
                    <ul>
                      {sciProjects.map(el => <li key={el}>{el}</li>)}
                    </ul>

                    <h4>Рецензування</h4>
                    <BlockContent
                      blocks={reviewing}
                      projectId={clientConfig.projectId}
                      dataset={clientConfig.dataset}
                    />
                    <h4>Рецензовані дисертаційні роботи</h4>
                    <BlockContent
                      blocks={reviewedDissertations}
                      projectId={clientConfig.projectId}
                      dataset={clientConfig.dataset}
                    />

                    <hr />

                    <h4>УМІННЯ ТА НАВИЧКИ</h4>

                    <h4>Мови: <span className="h5">
                      {languages.map(el => el).join(", ") + "."}
                    </span>
                    </h4>



                    <h4>Стажування</h4>
                    <ul>
                      {internship.map(el => <li key={el}>{el}</li>)}
                    </ul>
                    <h4>Сертифікати</h4>
                    <ul>
                      {certificates.map(el => <li key={el}>{el}</li>)}
                    </ul>
                    <h4>Нагороди та відзнаки</h4>
                    <ul>
                      {awards.map(el => <li key={el}>{el}</li>)}
                    </ul>

                    <hr />

                    <h4>НАВЧАЛЬНІ ДИСЦИПЛІНИ</h4>
                    <ul>
                      {teachingSubjectList.map(el =>
                        <li key={el.teachingSubjectId}>
                          {el.teachingSubjectName} - ID: {el.teachingSubjectId}
                        </li>)}
                    </ul>

                    <hr />

                    <h4>БІОГРАФІЯ</h4>
                    <BlockContent
                      blocks={bio}
                      projectId={clientConfig.projectId}
                      dataset={clientConfig.dataset}
                    />
                  </div>
                </div>
              </div>

              {/* <div> */}
              <Lightbox
                open={open}
                close={() => setOpen(false)}
                slides={galleryArray}
              />
              {/* </div> */}

            </div>

          </div>
          {/* <!-- End Feature Icons --> */}

        </div >
      </section >
      {/* <!--End Features Section-- > */}
    </>
  )
}


export default PersonInfo;

export async function getStaticPaths() {
  const query = `*[type=='person']{
slug{
  current
}
  }`;
  const persons = await client.fetch(query);
  const paths = persons.map((person) => ({
    params: {
      slug: person.slug.current
    }
  }));
  return {
    paths, fallback: 'blocking'
  }
}

export async function getStaticProps({ params: { slug } }) {

  const personItem = await client.fetch(chapterItemQuery("person", slug));

  const aboutItems = await client.fetch(chapterTitleQuery("about"));
  const specialitiesItems = await client.fetch(chapterTitleQuery("specialities"));
  const bachelorItems = await client.fetch(chapterTitleQuery("bachelor"));
  const masterItems = await client.fetch(chapterTitleQuery("master"));

  return {
    props: {
      personItem,
      aboutItems,
      specialitiesItems,
      bachelorItems,
      masterItems,
    }
  }
}