import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import { client } from "../lib/client";

const inter = Inter({ subsets: ['latin'] })

export default function Home({ fetchedData }) {

  console.log(fetchedData);
  console.log(fetchedData[0].title)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
        <div className={styles.center}>{fetchedData[0].title}...</div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const fetchedData = await client.fetch(`*[_type == "movie"]`);

  return {
    props: {
      fetchedData
    }
  };
}