import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import electricMan from '../public/assets/img/hero-img.png'

import { client } from "../lib/client";

const inter = Inter({ subsets: ['latin'] })

export default function Home({ fetchedData }) {

  // console.log(fetchedData);
  // console.log(fetchedData[0].title)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>


        {/* ======= Hero Section ======= */}
        <section id="hero" className="hero d-flex align-items-center">
          <div className="container">
            <div className="row">
              <div className="col-lg-6 d-flex flex-column justify-content-center">
                <h1 data-aos="fade-up">Кафедра <br /> Електричної Інженерії ТНТУ ім. І.Пулюя</h1>
                <h2 data-aos="fade-up" data-aos-delay="400">Спеціальність 141 <br /> `Електроенергетика, електротехніка та електромеханіка`</h2><br />
                <h3 data-aos="fade-up" data-aos-delay="400" className="h5">Шукаємо талановитих абітурієнтів, які хочуть пов`язати своє життя з електротехнікою та інженерією</h3>
                <div data-aos="fade-up" data-aos-delay="600">
                  <div className="text-center text-lg-start">
                    <a href="#faq" className="btn-get-started scrollto d-inline-flex align-items-center justify-content-center align-self-center">
                      <span>Навчатись в нас</span>
                      <i className="bi bi-arrow-right"></i>
                    </a>
                  </div>
                </div>
              </div>
              <div className="col-lg-6 hero-img" data-aos="zoom-out" data-aos-delay="200">
                <Image
                  src={electricMan}
                  alt="Picture of the man near electric box"
                  className="col-lg-6 hero-img"
                  data-aos="zoom-out"
                  data-aos-delay="200"
                  style={{ width: '100%', height: '100%' }}
                />
              </div>
            </div>
          </div>
        </section>
        {/* End Hero */}


      </main>
    </>
  )
}

export async function getStaticProps() {
  const fetchedData = await client.fetch(`*[_type == "movie"]`);

  return {
    props: {
      fetchedData
    }
  };
}