import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import electricMan from '../public/assets/img/hero-img.png'

import { client } from "../lib/client";

const inter = Inter({ subsets: ['latin'] })

export default function Home({ fetchedData }) {

  console.log(fetchedData[0].title)

  return (
    <>
      <Head>
        <title>Кафедра електричної інженерії ТНТУ :: Головна сторінка</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>


        {/* ======= Hero Section ======= */}
        <section id="hero" className="hero d-flex align-items-center">
          <div className="container">
            <div className="row">
              <div className="col-lg-6 d-flex flex-column justify-content-center">
                <h1 data-aos="fade-up">Кафедра <br /> Електричної Інженерії ТНТУ ім. І.Пулюя</h1>
                <h2 data-aos="fade-up" data-aos-delay="400">Спеціальність 141 <br /> &ldquo;Електроенергетика, електротехніка та електромеханіка&rdquo;</h2><br />
                <h3 data-aos="fade-up" data-aos-delay="400" className="h5">Шукаємо талановитих абітурієнтів, які хочуть пов`язати своє життя з електротехнікою та інженерією</h3>
                <div data-aos="fade-up" data-aos-delay="600">
                  <div className="text-center text-lg-start">
                    <a href="#faq" className="btn-get-started scrollto d-inline-flex align-items-center justify-content-center align-self-center">
                      <span>Навчатись в нас</span>
                      <i className="bi bi-arrow-right"></i>
                    </a>
                  </div>
                </div>
              </div>
              <div className="col-lg-6 hero-img" data-aos="zoom-out" data-aos-delay="200">
                <Image
                  src={electricMan}
                  alt="Picture of the man near electric box"
                  className="img-fluid"
                  style={{ width: '100%', hight: '100%' }}
                />
              </div>
            </div>
          </div>
        </section>
        {/* End Hero */}




        {/* ------------------------------------------------------------------------------- */}

        {/* ======= Links Section ======= */}
        <section id="contact" className="contact">
          <div className="container" data-aos="fade-up">
            <header className="section-header">
              <h2>Структура</h2>
              <p>Карта сайту</p>
            </header>

            <div className="row gy-4">

              <div className="col">

                <div className="row gy-4 my-font-size">

                  <div className="col-lg-4 col-md-6 col-sm-12">
                    <div className="info-box">
                      <i className="bi bi-mortarboard"></i>
                      <h3>Про кафедру</h3>
                      <p><a href="kolektyv.aspx"><i className="bi bi-arrow-right"></i>Колектив кафедри</a></p>
                      <p><a href="obovjazky.aspx"><i className="bi bi-arrow-right"></i>Розподіл обов’язків</a></p>
                      <p><a href="istoria.aspx"><i className="bi bi-arrow-right"></i>Історія кафедри</a></p>
                      <p><a href="events.aspx"><i className="bi bi-arrow-right"></i>Події на кафедрі</a></p>
                      <p><a href="osvprogramy.aspx"><i className="bi bi-arrow-right"></i>Освітні програми</a></p>
                      <p><a href="navplany.aspx"><i className="bi bi-arrow-right"></i>Навчальні плани</a></p>
                      <p><a href="laborator.aspx"><i className="bi bi-arrow-right"></i>Навчальні лабораторії</a></p>
                      <p><a href="fotoarchiv.aspx"><i className="bi bi-arrow-right"></i>Фотоархів кафедри</a></p>
                      <p><a href="video.aspx"><i className="bi bi-arrow-right"></i>Відеоархів кафедри</a></p>
                      <p><a href="kadry.aspx"><i className="bi bi-arrow-right"></i>Працювали на кафедрі</a></p>
                    </div>
                  </div>

                  <div className="col-lg-4 col-md-6 col-sm-12">
                    <div className="info-box">
                      <i className="bi bi-lightbulb"></i>
                      <h3>Наука</h3>
                      <p><a href="naukova-robota.aspx"><i className="bi bi-arrow-right"></i>Наукова робота кафедри</a></p>
                      <p><a href="naukovi-publikaсii.aspx"><i className="bi bi-arrow-right"></i>Головні наукові публікації</a></p>
                      <p><a href="naukovi-proekty.aspx"><i className="bi bi-arrow-right"></i>Наукові проекти</a></p>
                      <p><a href="aspirantura.aspx"><i className="bi bi-arrow-right"></i>Аспірантура</a></p>
                      <p><a href="labenergysaving.aspx"><i className="bi bi-arrow-right"></i>Лабораторія енергоощадності</a></p>
                      <p><a href="zahysty.aspx"><i className="bi bi-arrow-right"></i>Захисти дисертацій</a></p>
                      <p><a href="conf-2015.aspx?lang=uk"><i className="bi bi-arrow-right"></i>Конференція - 2015</a></p>
                      <p><a href="conf-2018.aspx?lang=uk"><i className="bi bi-arrow-right"></i>Конференція - 2018</a></p>
                      <p><a href="presa.aspx"><i className="bi bi-arrow-right"></i>Публікації у пресі</a></p>
                    </div>
                  </div>

                  <div className="col-lg-4 col-md-6 col-sm-12">
                    <div className="info-box">
                      <i className="bi bi-emoji-sunglasses"></i>
                      <h3>Студенту</h3>
                      <p><a href="navproces.aspx"><i className="bi bi-arrow-right"></i>Графіки навчального процесу</a></p>
                      <p><a href="dyscypliny.aspx"><i className="bi bi-arrow-right"></i>Навчальні дисципліни кафедри</a></p>
                      <p><a href="literatura.aspx"><i className="bi bi-arrow-right"></i>Навчально-методична література</a></p>
                      <p><a href="praktyky.aspx"><i className="bi bi-arrow-right"></i>Практики</a></p>
                      <p><a href="kurs-proekt.aspx"><i className="bi bi-arrow-right"></i>Курсове проектування</a></p>
                      <p><a href="dypl-proekt.aspx"><i className="bi bi-arrow-right"></i>Дипломне проектування</a></p>
                      <p><a href="repozytorij.aspx"><i className="bi bi-arrow-right"></i>Репозиторій файлів</a></p>
                      <p><a href="temyproektiv.aspx"><i className="bi bi-arrow-right"></i>Тематика дипломного проектування</a></p>
                      <p><a href="dni-fakultetu.aspx"><i className="bi bi-arrow-right"></i>Дні факультету</a></p>
                      <p><a href="travel.aspx"><i className="bi bi-arrow-right"></i>Тематичні екскурсії</a></p>
                      <p><a href="olimpiady-em.aspx"><i className="bi bi-arrow-right"></i>Участь в олімпіадах з ЕМ</a></p>
                      <p><a href="olimpiady-ese.aspx"><i className="bi bi-arrow-right"></i>Участь в олімпіадах з ЕСЕ</a></p>
                    </div>
                  </div>

                  <div className="col-lg-4 col-md-6 col-sm-12">
                    <div className="info-box">
                      <i className="bi bi-globe"></i>
                      <h3>Міжнародні зв’язки</h3>
                      <p><a href="mizhnar-spivpracia.aspx"><i className="bi bi-arrow-right"></i>Міжнародна співпраця</a></p>
                      <p><a href="mizhnar-proekty.aspx"><i className="bi bi-arrow-right"></i>Участь у міжнародних проектах</a></p>
                      <p><a href="mizhnar-dyplomy.aspx"><i className="bi bi-arrow-right"></i>Подвійні дипломи</a></p>
                      <p><a href="mizhnar-stazhuvannia.aspx"><i className="bi bi-arrow-right"></i>Стажування за кордоном</a></p>
                    </div>
                  </div>

                  <div className="col-lg-4 col-md-6 col-sm-12">
                    <div className="info-box">
                      <i className="bi bi-link-45deg"></i>
                      <h3>Посилання</h3>
                      <p><a href="kontakty.aspx"><i className="bi bi-arrow-right"></i>Контакти Кафедри</a></p>
                      <p><a href="http://tntu.edu.ua/"><i className="bi bi-arrow-right"></i>Головна сторінка університету</a></p>
                      <p><a href="http://tntu.edu.ua/?p=uk/about/contacts#page"><i className="bi bi-arrow-right"></i>Телефони та пошта підрозділів</a></p>
                      <p><a href="http://tntu.edu.ua/?p=uk/admission#page"><i className="bi bi-arrow-right"></i>Приймальна комісія</a></p>
                      <p><a href="http://tntu.edu.ua/?p=uk/structure/faculties/fpt#page"><i className="bi bi-arrow-right"></i>Деканат ФПТ</a></p>
                      <p><a href="gramoty.aspx"><i className="bi bi-arrow-right"></i>Відзнаки студентів</a></p>
                      <p><a href="wypusknyky-ei.aspx"><i className="bi bi-arrow-right"></i>Випускники кафедри ЕІ</a></p>
                      <p><a href="wypusknyky-em.aspx"><i className="bi bi-arrow-right"></i>Випускники кафедри ЕМ (2003-2018 роки)</a></p>
                      <p><a href="robota.aspx"><i className="bi bi-arrow-right"></i>Працевлаштування випускників</a></p>
                      <p><a href="fpt-sklad-nmk.aspx"><i className="bi bi-arrow-right"></i>Науково-методична комісія факультету</a></p>
                    </div>
                  </div>

                  <div className="col-lg-4 col-md-6 col-sm-12 justify-content-center">
                    <div className="info-box">
                      <i className="bi bi-emoji-laughing"></i>
                      <h3>Абітурієнту</h3>
                      <p><a href="abiturientu.aspx"><i className="bi bi-arrow-right"></i>Абітурієнту про спеціальність</a></p>
                      <p><a href="energomenedzher.aspx"><i className="bi bi-arrow-right"></i>Навики та уміння енергоменеджера</a></p>
                      <p><a href="cikavi-statti.aspx"><i className="bi bi-arrow-right"></i>Цікаві статті</a></p>
                    </div>
                  </div>

                </div>

              </div>

            </div>

          </div>

        </section>
        {/* End Links Section */}


      </main>
    </>
  )
}

export async function getStaticProps() {
  const fetchedData = await client.fetch(`*[_type == "movie"]`);

  return {
    props: {
      fetchedData
    }
  };
}